### PR TITLE
Fix or skip remaining failing tests in CI

### PR DESCRIPTION
**Pull request by rosteen**
Does what it says on the tin. This is so we can see green status checks on the CI before getting these examples working for tests.

### CODE REVIEW

**Comment by larrybradley** [comment]
This line: https://github.com/spacetelescope/slitlessutils/blob/main/tox.ini#L49 (`jupyter --paths`) needs to be removed to get `pytest` tests running.

**Comment by rosteen** [comment]
> This line: https://github.com/spacetelescope/slitlessutils/blob/main/tox.ini#L49 (`jupyter --paths`) needs to be removed to get `pytest` tests running.

Good call. I was just about to start looking into this, thanks for saving me some time!

**Comment by larrybradley** [comment]
They are running now, but the failures are real. 😅

**Comment by rosteen** [comment]
I opened https://github.com/spacetelescope/slitlessutils/issues/34 to remind us to fix some of the things I'm about to add skips for, since it's not actually used yet.

**Comment by rosteen** [comment]
The last failure looks like it's due to `drizzlepac` being incompatible with `numpy` 1.25.0. I opened https://github.com/spacetelescope/drizzlepac/issues/1601 over there to let them know about this, but didn't have time to fix it myself. So for now I'm pinning a max version of `numpy` here.

**Review by haticekaratay — APPROVED** [review]

**Pull request merged**
