### PR TITLE
Ensure number of processes is not 0 in multithreading

### LINKED ISSUE #74: CI failing on Ubuntu
https://github.com/spacetelescope/slitlessutils/pull/73 added a test that is passing on MacOS but is failing on Ubuntu. The 3.9 failure looks like version conflicts with Numpy, but the 3.11 failure appears to be a potentially real bug involving multiprocessing:

```
>       pdtfiles = tab(data, sources)  # noqa: F841

/home/runner/work/slitlessutils/slitlessutils/.tox/py311-test-cov/lib/python3.11/site-packages/slitlessutils/tests/test_acs_grism.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/slitlessutils/slitlessutils/.tox/py311-test-cov/lib/python3.11/site-packages/slitlessutils/core/modules/module.py:114: in __call__
    results = pool(data, sources, total=len(data), **kwargs)
/home/runner/work/slitlessutils/slitlessutils/.tox/py311-test-cov/lib/python3.11/site-packages/slitlessutils/core/utilities/pool.py:143: in __call__
    with mp.Pool(processes=ncpu) as p:
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.pool.Pool state=INIT pool_size=0>, processes = 0
initializer = None, initargs = (), maxtasksperchild = None
context = <multiprocessing.context.ForkContext object at 0x7f1d841e12d0>

    def __init__(self, processes=None, initializer=None, initargs=(),
                 maxtasksperchild=None, context=None):
        # Attributes initialized early to make sure that they exist in
        # __del__() if __init__() raises an exception
        self._pool = []
        self._state = INIT
    
        self._ctx = context or get_context()
        self._setup_queues()
        self._taskqueue = queue.SimpleQueue()
        # The _change_notifier queue exist to wake up self._handle_workers()
        # when the cache (self._cache) is empty or when there is a change in
        # the _state variable of the thread that runs _handle_workers.
        self._change_notifier = self._ctx.SimpleQueue()
        self._cache = _PoolCache(notifier=self._change_notifier)
        self._maxtasksperchild = maxtasksperchild
        self._initializer = initializer
        self._initargs = initargs
    
        if processes is None:
            processes = os.cpu_count() or 1
        if processes < 1:
>           raise ValueError("Number of processes must be at least 1")
E           ValueError: Number of processes must be at least 1

/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/multiprocessing/pool.py:205: ValueError
```

@Russell-Ryan , any insight into what's going on here? Are you generally running this on Mac or do you have an Ubuntu machine?

### PR DESCRIPTION
**Pull request by rosteen**
Fixes #74 (hopefully), thanks to @pllim for the suggestion there.

### CODE REVIEW

**Comment by pllim** [comment]
Maybe it is time to drop Python 3.9. Python 3.13 beta is already out.

**Comment by pllim** [comment]
I think until https://github.com/spacetelescope/stregion/issues/19 (and any other things that might crop up after this one is fixed) is resolved, I don't think you can install this package on Windows. Did this package ever work on Windows before?

**Comment by pllim** [comment]
All the Linux jobs passed. 🤞

**Comment by rosteen** [comment]
> Maybe it is time to drop Python 3.9. Python 3.13 beta is already out.

I've been considering it.

**Comment by pllim** [comment]
> I've been considering it.

Unless you somehow need to use this package in a very old environment for some ultra stable pipeline that is slow to upgrade or frozen, there is no reason to keep supporting it.

**Comment by rosteen** [comment]
I bumped the python min version, after realizing that if we manage to update `drizzlepac` to use `regions` instead of `stregion`, `regions` is min 3.10 anyway. I think that's the path to getting the Windows tests working, so might as well do it now.

**Comment by pllim** [comment]
Looks like you still not gotten rid of stregion yet in your stack according to Windows failure.

`Failed to build stregion`

**Comment by rosteen** [comment]
> Looks like you still not gotten rid of stregion yet in your stack according to Windows failure.
> 
> `Failed to build stregion`

Right, that's what I was saying - drizzlepac uses stregion and so we'd need changes there.

**Comment by larrybradley** [comment]
AFAIK no one working on replacing `stregion` with `regions` in `drizzlepac`.  If that's the case, they should at least be updating `stregion`.

**Comment by rosteen** [comment]
> AFAIK no one is working on replacing `stregion` with `regions` in `drizzlepac`. If that's the case, they should at least be updating `stregion`.

That was also my understanding, which is why I was planning to hack on it later this week if I have time 😬

**Comment by pllim** [comment]
If you cannot control upstream, your option would be down to making drizzlepac option and not install it on Windows. Or dropping Windows support altogether. (A lot of HST tools have a history of not supporting Windows due to resource limitations.)

**Comment by rosteen** [comment]
I'll merge this since the scope was to fix the Ubuntu tests. Windows is a separate issue.

**Pull request merged**
