### PR TITLE
Add function to group filenames by position angle

### PR DESCRIPTION
**Pull request by rosteen**
Needs tests, and I'll need to address conflicts once #28 is merged. Also, the distance threshold value is completely arbitrary at the moment pending input from someone with a better idea of typical PA values/differences.

### CODE REVIEW

**Comment by haticekaratay** [comment]
Hi @rosteen, Can you add the edge cases of degrees 0.01 deg and 359.9 deg to your test cases to see if they are grouped correctly?

**Comment by rosteen** [comment]
> Hi @rosteen, Can you add the edge cases of degrees 0.01 deg and 359.9 deg to your test cases to see if they are grouped correctly?

Done! And this caught an error with my distance calculation (although I don't know if PAs are limited to +/-180, in which case it wouldn't have come up).

**Comment by larrybradley** [comment]
Don't (4.05, 4.1) and (4.15, 4.2) also meet the constraint?  In general, there won't be a unique solution based only on angle differences.

**Comment by Russell-Ryan** [comment]
> Doesn't (4.05, 4.1) and (4.15, 4.2) also meet the constraint? In general, there won't be a unique solution based only on angle differences.

Sure.  I guess you'd have to take this as a starting point and find ways of carving up "possible" groups based on some additional requirement(s):
1) minimize the number of total groups (which is really just a means of saying, maximze the number of images per group --- the usual goal in drizzling).  This would naturally avoid the case you mentioned, as [(4,), (4.05, 4.1), (4.15, 4.2), (4.25,)] has more groups than [(4, 4.05), (4.1, 4.15), (4.2, 4.25)].  
2) avoid singleton groups --- as singletons obviate the use of drizzle.
Either of these is what a user would do empirically, when selecting which of their data to drizzle.

Yeah, this is a very tricky problem.

**Comment by rosteen** [comment]
>     1. minimize the number of total groups (which is really just a means of saying, maximize the number of images per group --- the usual goal in drizzling).  This would naturally avoid the case you mentioned, as [(4,), (4.05, 4.1), (4.15, 4.2), (4.25,)] has more groups than [(4, 4.05), (4.1, 4.15), (4.2, 4.25)].

Sounds like we want to restrain the maximum intra-cluster distance instead of limiting the maximum distance between the closest members of two clusters to merge them (what the code is currently doing). I think I can do this by either changing the `linkage` parameter or using a slightly different clustering algorithm. 

>     2. avoid singleton groups --- as singletons obviate the use of drizzle.

But what if there legitimately are singletons in the input? Currently the implemented clustering properly identifies those and we log a warning. We don't want to force actual singletons into a group, since as you said it would result in a flawed mosaic.

No automated grouping like this will be perfect for every edge case

**Comment by rosteen** [comment]
Of course, a maximum intra-cluster separation constraint doesn't address @larrybradley's point that there isn't a unique solution even in that case. As long as users can fall back on specifying the groupings to drizzle manually, I don't think we need to shoot for perfection in every edge case (since I don't think it's actually possible to do in an automated fashion).

**Comment by rosteen** [comment]
@Russell-Ryan I switched to `complete` linkage to implement the max intra-cluster distance constraint, you can see from the new test that `[360.0, 0.01, 0.05, 0.09]` get clustered as `[360.0, 0.01]` and `[0.05, 0.09]` even though the distance between 0.01 and 0.05 is less than the maximum PA difference.

**Comment by rosteen** [comment]
@Russell-Ryan I'm going to go ahead and merge this. If you decide the most recent update wasn't sufficient to fix the issue you raised, we can work on that more in a follow-up PR.

**Comment by Russell-Ryan** [comment]
No, there will definitely be singletons from time-to-time.  But singletons we do not want to inadvertently create singletons because of a corner case in the method, as singletons will not get any CR clipping.  I'll play around with the new feature now.  I agree, this is a very hard problem, but I do think we can get the edge cases provided we apply all necessary conditions.

**Review by Russell-Ryan — APPROVED** [review]
I played around with it.  Looks good.  I noticed that it still runs into numerical precision problems, which I'm surprised by.  But that is probably well beyond the scope of this ;).  

FWIW.  I tried it on various combinations of PAs, up to and including 400 different values (just to get a sense of scaling of the clustering algorithm).  And it seems to do fine.  I tried 1000 PAs, and it got pretty slow.  I think 1000 files is absurd (as the most I've ever heard of are ~600 files and that is for a very select experiment on Roman).  So I think it's safe to accept several hundred as a safe upper limit. It might be worth adding a cavaet to the docstring that warns of CPU performance if the number is large (>~600).  I don't think we should worry about a legit check, as I think it's unlikely to EVER happen for HST/JWST.

But this looks really good to me!

**Pull request merged**
