### PR TITLE
updated configuration object and reference file management

### PR DESCRIPTION
**Pull request by Russell-Ryan**
This updates the configuration object to retrieve the reference file(s) from box, unpack them in $home/.slitlessutils, and set the `refpath` to the most recent reference file version number (as given in the VERSION.json file).

### CODE REVIEW

**Comment by Russell-Ryan** [comment]
Thanks for looking at this @rosteen.  

As for the version, that's a good idea.  One can technically get that, but it's kinda convoluted, so I'll add a `@property` to streamline that.  

As for the downloading.  I'll look into the astropy function to download files, it sounds like it might streamline a few things.  But, I am really skeptical about automatically downloading reference files, as it can mean that the results a user gets will/may change unbeknownst to them as the files evolve.  While it's nice to use the latest-greatest, it will/may complicate a user's experience.  But I'll have a look.

**Comment by rosteen** [comment]
> But, I am really skeptical about automatically downloading reference files, as it can mean that the results a user gets will/may change unbeknownst to them as the files evolve.

Is this worse than a user getting _wrong_ results because something has been update/fixed in the config files, and they don't know that they need to update them? I know you went back and forth with @duytnguyendtn about this, and I don't feel particularly strongly about it, I just see this as the worse failure mode. Really I think that either way we go we should raise a warning to the user that either (a) there are more up-to-date files and they should get them, or (b) that there were more up-to-date files and the code downloaded them automatically.

**Comment by Russell-Ryan** [comment]
I think the raising a warning is a good compromise.  Because, I think _wrong_ can sometimes be tricky to determine. Either way, I expect people to get concerned with they see the results changing without a simple thing to point to.  

But I like the warning, that gives them the awareness and avoids changing their results without their permission or understanding.  Users will ignore warnings at their peril.  That said, I'm not sure of a good way to do this, since it's a tar file on box.  We don't want to download the entire tar file every time they import the package (as it's ~100 Mb and only going to grow), so we would need to:

1. store the `version.json` file elsewhere (ie outside of the tar file, or maybe in addition to the tar file)
2. not host a tar file, but rather host a directory
3. figure out if one can get a single file from the remotely-stored tar file. 
4. not delete the file (as I'm doing) --- I think this is what you were suggesting --- and just compare files that way?  

I think I'll research the #3 option, as that would be the easiest to implement.  I'm not a fan of #1 as that means, we need to curate two (identical) files.  I really like #2, but that just seems like a significant amount of work.  Option #4 seems pretty easy as well, but we'd just be saving the file to act as a sentinel, which seems like a lotta disk usage for a simple task (so I worry about filling their directories with stuff).  Do you have any ideas?

Could we merge this PR in the meantime, as I think it does the job it's supposed to do.  And I'll submit a new PR once we have the warning system in place?

**Comment by rosteen** [comment]
> gives them the awareness and avoids changing their results without their permission or understanding

I think this is solved by coupling downloading a newer version of the config files with upgrading your version of `slitlessutils`. What I'm imagining is:

1) We keep what you do now (deleting the tar file after it's unpacked).
2) We add a check to see if the version number stored somewhere in the source code (perhaps add `config_version` to `_version.py`) matches the highest version directory number in `.slitlessutils/`. This triggers the download if needed.
3) When new config files are available, `config_version` from (2) gets updated and (this is the crucial part) we release a new version of `slitlessutils` with that update.

This would mean that the user is only getting new config files if they've actually updated their version of `slitlessutils`, which is a sensible trigger for potentially getting different results and requires the user to actually take action rather than maybe updating the config files every time `slitlessutils` is run. This strategy also avoids the undesirable aspects of storing the tar file on disk and/or needing to download the whole tarfile to check versions.

All of this said - I would be ok merging this PR and following up in another PR with whatever strategy we end up going with (and any warnings for the user).

**Comment by Russell-Ryan** [comment]
I guess I'm not totally understanding.  In the `.slitlessutils/` dir, the version number is used to name the subdirectories (for example `.slitlessutils/1.1.1/` and the `version.json` file is in there also.  This way, if a power-user comes along they can still add additional subdirectories and/or tweak files. 

The problem I'm having is that the tar-archive stored on box has the `version.json` file inside of it, so I don't see how to test if the tar-archive has changed without downloading the entire file.  The code does not "know" the reference file library version number, other than what it detects from the `.slitlessutils/` base directory.  

This problem arises because the box file has an incomprehensible name.  When I upload the files, I give them names like `slitlessutils_config_1.1.2.tar.gz`, but that gets mangled.  I think the only way out is to maintain a second file on the box archive (like LATEST.txt or something) that knows some light-weight versioning.

**Comment by rosteen** [comment]
Forget about the file on Box, my proposal doesn't involve that file at all for the version check.

> The code does not "know" the reference file library version number

Right, I'm saying we change this. What I'm saying is that we add the reference file library version number to the code, and when the reference files are updated that number also gets updated in the code in a tiny PR. This way every released version of slitlessutils has an associated reference file version. Not all `slitlessutils` releases will have an updated ref file version, but every ref file update will have an associated `slitlessutils` release to update the version number in the code to check against.

**Comment by Russell-Ryan** [comment]
Ok.. we can look at something like that.  But what do we do to merge the PR?

**Comment by rosteen** [comment]
I'll merge it, was just waiting to resolve that conversation.

**Pull request merged**
